[server]
# Протокол: http, https, socket
protocol = http
# Хост: 0.0.0.0 = слушать все интерфейсы
http_addr = 0.0.0.0
# Порт по умолчанию 3000
http_port = 3000
# Домен для генерации ссылок
domain = 10.0.0.2

[security]
# Отключаем регистрацию новых пользователей
disable_initial_admin_creation = false
# Разрешаем анонимный доступ
# allow_sign_up = false

[auth.anonymous]
enabled = false

[paths]
# Хранение данных
data = /var/lib/grafana
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
